<div class="upsell">
<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
    <div class="page-title1">
    <strong><?php echo $this->__('You may also be interested in the following product(s)') ?></strong>
    </div>
    <table class="products-grid" id="upsell-product-table">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <tr>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <td><div class="grid_prod">
                <div class="prod_image"> <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(120,125) ?>" width="120" height="125" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a></div>
               <div class="prod_image_detail">                 
		<div class="new_product-name">				  
		<h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>">
		<?php $pname =  $this->htmlEscape($_link->getName());
		if(strlen($pname) > 28 )
		{
		echo substr($pname,0,25).'...'; 
		}
		else 
		{
		echo $pname; 
		}
			
		 ?>
		</a></h3></div>
             <div class="new_prod_price">   <?php echo $this->getPriceHtml($_link, true, '-upsell') ?></div>
                <?php echo $this->getReviewsSummaryHtml($_link) ?></div></div>
            </td>
            <?php else: ?>
            <td class="empty">&nbsp;</td>
            <?php endif; ?>
        <?php endfor; ?>
        </tr>
    <?php endfor; ?>
    </table>
    <script type="text/javascript">decorateTable('upsell-product-table')</script>
</div>
<?php endif ?>
</div>
