
<div class="page-title">
      <h1><?php echo $this->__('My Dashboard') ?></h1>
</div>
<div class="dashboard">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    
        <div style="text-align:left;">
            <h2><?php echo $this->__('Account Information') ?></h2>
        </div>
        <?php echo $this->getChildHtml('info') ?>
        <?php echo $this->getChildHtml('address') ?>
   
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>
