<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<div class="cross_sell_prod">
<?php if($this->getItemCount()): ?>
<div class="crosssell">
    <div class="page-title"><h1><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h1></div>
   <div class="category-products"> <ul id="crosssell-products-list" class="products-grid">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item"><div class="grid_prod">
              <div class="prod_image"><a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(135,135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
		</div>
            <div class="prod_image_detail">
        <div class="new_product-name"><h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>">
	<?php $prod_name = $this->htmlEscape($_item->getName());  if(strlen($prod_name) > 25) {echo substr($prod_name,0,23)."...";}else {echo $prod_name;}?>
	</a></h3></div>
               <div class="new_prod_price"> <?php echo $this->getPriceHtml($_item, true) ?></div>
               <div class="new_prod_btn"> <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button></div>
              <?php /*  <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                        <li><!--span class="separator">|</span--> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                    <?php endif; ?>
                </ul> */?>
            </div>
       </div> </li>
    <?php endforeach; ?>
    </ul></div>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>
</div>
