<div class="footer"><center>

<div id="footerblock">   
<!--<div class="mar_t2 allborder">
	<div class="dldivt"> 		
	<dl><dt>Company Info</dt>
	<dd><a href="<?php echo $this->getUrl('')?>about-us">About Us</a> </dd>
	<dd><a href="<?php echo $this->getUrl('')?>location_working">Location &amp; Working Hours</a> </dd>
	<dd><a href="<?php echo $this->getUrl('')?>catalogsearch/term/popular/">Search Terms</a> </dd> 
	<dd><a href="<?php echo $this->getUrl('')?>catalog/seo_sitemap/category/">Site Map</a> </dd> 
	<dd><a href="<?php echo $this->getUrl('')?>our_guarantee">Our Guarantee</a> </dd>
	</dl> 		
	<dl><dt>Customer Service</dt>
	<dd><a href="<?php echo $this->getUrl('')?>contacts/">Contact Us</a> </dd>
	<dd><a href="<?php echo $this->getUrl('')?>track_your_order" >Track Your Order</a> </dd>
	<dd><a href="<?php echo $this->getUrl('')?>help" >Help</a> </dd>  
	</dl> 		
	<dl><dt>Shipping &amp; Returns</dt>
	<dd><a href="<?php echo $this->getUrl('')?>shipping_guide">Shipping Guide</a> </dd>
	<dd><a href="<?php echo $this->getUrl('')?>return_policy" >Return Policy</a> </dd>
	<dd><a href="<?php echo $this->getUrl('')?>locations_ship_to">Locations We Ship To</a> </dd>
	<dd><a href="<?php echo $this->getUrl('')?>estimate_delivery_time" >Estimate Delivery Time</a> </dd>
	</dl> 		
	<dl style="margin-right: 0px;"><dt>Security &amp; Privacy</dt>
	<dd><a href="<?php echo $this->getUrl('')?>privacy_policy">Privacy Policy</a> </dd>
	<dd><a href="<?php echo $this->getUrl('')?>terms_of_use">Terms of Use</a> </dd>
	</dl>
	</div>
</div>-->

		
<div class="copyright">
<div style="float: left;">
<?php echo $this->getCopyright() ?>
</div>
<div style="float: right;">
<!--<a href="http://www.magikcommerce.com/themes" target="_blank">Magento Themes </a>&nbsp;&nbsp; <a href="http://www.magikcommerce.com/extensions" target="_blank">Magento Extensions</a>-->
</div>
</div></div>
</center>
</div>
