<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
    <div class="header">
       <div class="header_right">
          <div class="header_top"><?php echo $this->getChildHtml('topSearch') ?>
			<div class="icon"> 
				<ul>
					<!--<li><a href="#"><img align="absmiddle" alt="" src="<?php echo $this->getSkinUrl('images/facebook.png'); ?>"></a></li>
					<li><a href="#"><img align="absmiddle" alt="" src="<?php echo $this->getSkinUrl('images/twitter.png'); ?>"></a></li>
					<li><a href="#"><img align="absmiddle" alt="" src="<?php echo $this->getSkinUrl('images/rss-small.png'); ?>"></a></li>
					<li><a href="#"><img align="absmiddle" alt="" src="<?php echo $this->getSkinUrl('images/mail.png'); ?>"></a></li>-->
				</ul>		
			</div>
          </div>      
          <div class="toplinks"><?php echo $this->getChildHtml('topLinks') ?><div class="welcome-msg"><?php echo $this->getWelcome() ?></div></div> 
       </div>
       <div class="logo">
        <?php if ($this->getIsHomePage()):?>
        <h1 id="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class=""><img src="<?php echo $this->getSkinUrl('images/logo.jpg'); ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else:?>
        <h1 id="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" id="logo"><img src="<?php echo $this->getSkinUrl('images/logo.jpg'); ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php endif?>
        </div>
        <?php echo $this->getChildHtml('topMenu') ?>
   </div>
 



