<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
    <div class="header">
        <div class="header_left">
                选择分店:&nbsp;<select><option>上大34店</option></select>&nbsp;&nbsp;
        </div>
        <div class="header_right">
                <div class="header_top">
                <div class="toplinks"><?php echo $this->getChildHtml('topLinks') ?><div class="welcome-msg"><?php echo $this->getWelcome() ?></div></div>
        </div>
        </div>
        <div class="logo">
        <?php if ($this->getIsHomePage()):?>
        <h1 id="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class=""><img src="<?php echo $this->getSkinUrl('images/logo.jpg'); ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else:?>
        <h1 id="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" id="logo"><img src="<?php echo $this->getSkinUrl('images/logo.jpg'); ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php endif?>
        </div>
        <?php echo $this->getChildHtml('topMenu') ?>
   </div>
 



