<div class="page-title">
    <h2 class="page-title1"><?php echo $this->__('All Tags') ?></h2>
</div>
<?php if( sizeof($this->getTags()) > 0 ): ?>
    <ul class="tags-list">
        <?php foreach ($this->getTags() as $_tag): ?>
            <li><a href="<?php echo $_tag->getTaggedProductsUrl() ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->htmlEscape($_tag->getName()) ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p class="note-msg"><?php echo $this->__('There are no tags available.') ?></p>
<?php endif; ?>
