<div class="std">
<div class="tags">
    <strong><?php echo $this->__('Product Tags') ?></strong>
    <?php echo $this->getChildHtml('list_before')?>
    <?php if( $this->getCount() ): ?>
    
    <ul id="<?php echo $this->getUniqueHtmlId('product-tags_'); ?>" class="form-add-tags">
    <span><?php echo $this->__('Other people marked this product with these tags:') ?></span>
        <?php echo $this->renderTags('<li><a href="%1$s">%2$s</a> (%3$s)</li>') ?>
    </ul>
    <script type="text/javascript">
        decorateGeneric($("<?php echo $this->getUniqueHtmlId('product-tags_'); ?>").select('li'), ['first', 'last']);
    </script>
    <?php endif; ?>
    <form id="addTagForm" action="<?php echo $this->getFormAction(); ?>" method="get">
        <div class="form-add-tags">
            <label for="productTagName"><?php echo $this->__('Add Tags:') ?></label><br /><br />
               <div class="input-box">
                <input type="text" class="input-text required-entry" name="productTagName" id="productTagName" style="width:450px;height:18px;" />
            
            <button type="button" title="<?php echo $this->__('Add Tags') ?>" class="button" onclick="submitTagForm()">
                
                    <span><?php echo $this->__('Add Tags') ?></span>
              
            </button>
	   </div>
         <p class="note"><?php echo $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
        </div>
    </form>
    
    <script type="text/javascript">
    //<![CDATA[
        var addTagFormJs = new VarienForm('addTagForm');
        function submitTagForm(){
            if(addTagFormJs.validator.validate()) {
                addTagFormJs.form.submit();
            }
        }
    //]]>
    </script>
</div>
</div>
