<div class="newproducts">
<?php 
//$_products = $this->getProductCollection()
//			->addAttributeToSelect('*')
//			->addAttributeToSort('created_at', 'desc')
//			->setPageSize('16');
//			echo var_dump($_products->getItems());
//if ($_products && $_products->getSize()):
if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="category-products">
<div class="page-title">
<h1><?php echo $this->__('New Products') ?></h1>
</div>
<?php $_columnCount = $this->getColumnCount(); ?>
	<ul class="products-grid">
    <?php $i=0; foreach ($_products->getItems() as $_product): ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
<div class="grid_prod">
              <div class="prod_image">  <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a></div>
              <div class="prod_image_detail"><div class="new_product-name">
                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php $prod_name = $this->htmlEscape($_product->getName()) ;
				 if(strlen($prod_name) > 25) {echo substr($prod_name,0,22)."...";}else {echo $prod_name;}?></a></h3>
</div>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            <div class="new_prod_price">     <?php echo $this->getPriceHtml($_product, true, '-new') ?></div>
                <div class="new_prod_btn">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
					<?php if ($this->helper('wishlist')->isAllow()) : ?>
						<p class="pbutton"><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></p>
					<?php endif; ?>
					</div>
                    <!--<div class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <p><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></p>
                        <?php endif; ?>
                        <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                            <p><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></p>
                        <?php endif; ?>
                    </div>-->
                
</div>
</div>
            </li>
    <?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>
</div>
