<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<!--div class="nav-container"><div class="header_inner1"-->
    <ul id="nav">
		<li><a href="<?php echo $this->getUrl('') ?>">首页</a></li>
    </ul>
<!--/div></div-->
